version: '3.8'

services:
  db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: movieshop
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
    ports:
      - "3307:3306"

  my-spring-app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/movieshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - db
